Update blurhash dependency
Baseflow/octo_image pull request #23
Opened 2022-04-23 10:09 UTC by Jordan1122

### :sparkles: Dependency update

Other packages rely on this, and it still uses the old version of blurhash

2022-04-28 07:18 UTC, Jordan1122 commented
@renefloor

2022-04-28 13:07 UTC, renefloor requested changes
Good point, but there is no need to drop support for v6, as it is not breaking (for us).

2022-04-28 13:07 UTC, renefloor commented on pubspec.yaml
> +  flutter_blurhash: ^0.7.0
```suggestion
  flutter_blurhash: '>=0.6.0 <0.8.0' 
```

2022-05-03 08:47 UTC, Jordan1122 commented
@renefloor is it ok now?

2022-05-10 07:21 UTC, Jordan1122 commented
@renefloor I don't know if this will solve all of the problems, but can you approve this?

2022-05-16 17:53 UTC, merged